name: ${project.name}
main: me.rayzr522.decoheads.DecoHeads
version: ${project.version}
description: ${project.description}
author: Rayzr522
url: ${project.url}
softdepend: [Vault]
commands:
  decoheads:
    description: Opens the DecoHeads inventory
    aliases: [dh, heads]
    usage: Oops! Something went wrong!
  decoheadsadmin:
    description: DecoHeads admin commands
    aliases: [dhadmin, dha]
    usage: Oops! Something went wrong!